route:
  repeat_interval: 5m
  group_interval: 5m
  receiver: 'rocketchat'
receivers:
  - name: 'rocketchat'
    webhook_configs:
      - send_resolved: true
        url:  #Webhook URL taken from rocketchat
